/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    projects: Project;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    project_page_settings: ProjectPageSetting;
    site_settings: SiteSetting;
  };
  globalsSelect: {
    project_page_settings: ProjectPageSettingsSelect<false> | ProjectPageSettingsSelect<true>;
    site_settings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Flexible pages composed from dynamic content blocks.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  pageTitle?: string | null;
  /**
   * Path segment used by the frontend, e.g. /about.
   */
  url?: string | null;
  contents?:
    | (
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageRichText';
          }
        | {
            topTitle?: string | null;
            leftTitle?: string | null;
            rightTitle?: string | null;
            colorReverse?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageHeading';
          }
        | {
            name: string;
            url: string;
            external?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageButton';
          }
        | {
            label?: string | null;
            title?: string | null;
            subtitle?: string | null;
            topPadding?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageProjectGrid';
          }
        | {
            title: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageContactForm';
          }
        | {
            enable: boolean;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageThreeDLetter';
          }
        | {
            title?: string | null;
            desc?: string | null;
            arrowText?: string | null;
            arrowLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageHeroSection';
          }
        | {
            topTitle?: string | null;
            leftTitle?: string | null;
            rightTitle?: string | null;
            contents?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            techs?:
              | {
                  icon: string | Media;
                  title: string;
                  id?: string | null;
                }[]
              | null;
            btnText?: string | null;
            btnLinks?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageAboutMeSection';
          }
        | {
            label?: string | null;
            title?: string | null;
            subtitle?: string | null;
            items?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageStatsSection';
          }
        | {
            label?: string | null;
            title?: string | null;
            subtitle?: string | null;
            items?:
              | {
                  name: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageTechStackSection';
          }
        | {
            tone?: ('default' | 'tinted' | 'dark') | null;
            centered?: boolean | null;
            label?: string | null;
            title?: string | null;
            subtitle?: string | null;
            primaryButtonText?: string | null;
            primaryButtonUrl?: string | null;
            primaryButtonExternal?: boolean | null;
            secondaryButtonText?: string | null;
            secondaryButtonUrl?: string | null;
            secondaryButtonExternal?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageCtaSection';
          }
        | {
            label?: string | null;
            title?: string | null;
            subtitle?: string | null;
            topPadding?: boolean | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            sidebarTitle?: string | null;
            details?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            socialLinks?:
              | {
                  label: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageProfileSection';
          }
        | {
            label?: string | null;
            title?: string | null;
            subtitle?: string | null;
            groups?:
              | {
                  items?:
                    | {
                        label: string;
                        value: number;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageSkillBarsSection';
          }
        | {
            tone?: ('default' | 'tinted' | 'dark') | null;
            label?: string | null;
            title?: string | null;
            subtitle?: string | null;
            items?:
              | {
                  iconText?: string | null;
                  title: string;
                  desc: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageCardGridSection';
          }
        | {
            label?: string | null;
            title?: string | null;
            subtitle?: string | null;
            topPadding?: boolean | null;
            methods?:
              | {
                  label: string;
                  value: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            cardTitle?: string | null;
            cardDescription?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageContactMethodsSection';
          }
      )[]
    | null;
  metaDesc?: string | null;
  enableBgHeading: boolean;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Portfolio projects with metadata, tags, and dynamic content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  title?: string | null;
  alias?: string | null;
  date?: string | null;
  desc?: string | null;
  tags?:
    | (
        | 'Web'
        | 'School Projects'
        | 'Movie Streaming'
        | 'Workshop'
        | 'Todo App'
        | 'Side Project'
        | 'Personal Website'
        | 'AI'
        | 'Final Year Project'
        | 'Mobile App'
        | 'Personal Blog'
        | 'Strapi CMS'
      )[]
    | null;
  img?: (string | null) | Media;
  cardStyle: 'blog' | 'portfolio' | 'terminal' | 'code';
  links?:
    | {
        name: string;
        links: string;
        id?: string | null;
      }[]
    | null;
  contents?:
    | (
        | {
            label?: string | null;
            title?: string | null;
            subtitle?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            scopeTitle?: string | null;
            scopeItems?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'projectOverviewSection';
          }
        | {
            label?: string | null;
            title?: string | null;
            subtitle?: string | null;
            name: string;
            items: {
              media?: (string | null) | Media;
              desc?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'projectsCarousel';
          }
        | {
            label?: string | null;
            title?: string | null;
            subtitle?: string | null;
            items?:
              | {
                  iconText?: string | null;
                  title: string;
                  desc: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'projectFeatureGridSection';
          }
        | {
            name?: string | null;
            contents?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'projectContents';
          }
        | {
            label?: string | null;
            title?: string | null;
            subtitle?: string | null;
            items?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            primaryButtonText?: string | null;
            primaryButtonUrl?: string | null;
            primaryButtonExternal?: boolean | null;
            secondaryButtonText?: string | null;
            secondaryButtonUrl?: string | null;
            secondaryButtonExternal?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'projectTechStackSection';
          }
        | {
            label?: string | null;
            title?: string | null;
            subtitle?: string | null;
            primaryButtonText?: string | null;
            primaryButtonUrl?: string | null;
            primaryButtonExternal?: boolean | null;
            secondaryButtonText?: string | null;
            secondaryButtonUrl?: string | null;
            secondaryButtonExternal?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'projectCtaSection';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  pageTitle?: T;
  url?: T;
  contents?:
    | T
    | {
        pageRichText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        pageHeading?:
          | T
          | {
              topTitle?: T;
              leftTitle?: T;
              rightTitle?: T;
              colorReverse?: T;
              id?: T;
              blockName?: T;
            };
        pageButton?:
          | T
          | {
              name?: T;
              url?: T;
              external?: T;
              id?: T;
              blockName?: T;
            };
        pageProjectGrid?:
          | T
          | {
              label?: T;
              title?: T;
              subtitle?: T;
              topPadding?: T;
              id?: T;
              blockName?: T;
            };
        pageContactForm?:
          | T
          | {
              title?: T;
              id?: T;
              blockName?: T;
            };
        pageThreeDLetter?:
          | T
          | {
              enable?: T;
              id?: T;
              blockName?: T;
            };
        pageHeroSection?:
          | T
          | {
              title?: T;
              desc?: T;
              arrowText?: T;
              arrowLink?: T;
              id?: T;
              blockName?: T;
            };
        pageAboutMeSection?:
          | T
          | {
              topTitle?: T;
              leftTitle?: T;
              rightTitle?: T;
              contents?: T;
              techs?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    id?: T;
                  };
              btnText?: T;
              btnLinks?: T;
              id?: T;
              blockName?: T;
            };
        pageStatsSection?:
          | T
          | {
              label?: T;
              title?: T;
              subtitle?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pageTechStackSection?:
          | T
          | {
              label?: T;
              title?: T;
              subtitle?: T;
              items?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pageCtaSection?:
          | T
          | {
              tone?: T;
              centered?: T;
              label?: T;
              title?: T;
              subtitle?: T;
              primaryButtonText?: T;
              primaryButtonUrl?: T;
              primaryButtonExternal?: T;
              secondaryButtonText?: T;
              secondaryButtonUrl?: T;
              secondaryButtonExternal?: T;
              id?: T;
              blockName?: T;
            };
        pageProfileSection?:
          | T
          | {
              label?: T;
              title?: T;
              subtitle?: T;
              topPadding?: T;
              body?: T;
              sidebarTitle?: T;
              details?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              socialLinks?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pageSkillBarsSection?:
          | T
          | {
              label?: T;
              title?: T;
              subtitle?: T;
              groups?:
                | T
                | {
                    items?:
                      | T
                      | {
                          label?: T;
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pageCardGridSection?:
          | T
          | {
              tone?: T;
              label?: T;
              title?: T;
              subtitle?: T;
              items?:
                | T
                | {
                    iconText?: T;
                    title?: T;
                    desc?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pageContactMethodsSection?:
          | T
          | {
              label?: T;
              title?: T;
              subtitle?: T;
              topPadding?: T;
              methods?:
                | T
                | {
                    label?: T;
                    value?: T;
                    url?: T;
                    id?: T;
                  };
              cardTitle?: T;
              cardDescription?: T;
              id?: T;
              blockName?: T;
            };
      };
  metaDesc?: T;
  enableBgHeading?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  alias?: T;
  date?: T;
  desc?: T;
  tags?: T;
  img?: T;
  cardStyle?: T;
  links?:
    | T
    | {
        name?: T;
        links?: T;
        id?: T;
      };
  contents?:
    | T
    | {
        projectOverviewSection?:
          | T
          | {
              label?: T;
              title?: T;
              subtitle?: T;
              content?: T;
              scopeTitle?: T;
              scopeItems?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        projectsCarousel?:
          | T
          | {
              label?: T;
              title?: T;
              subtitle?: T;
              name?: T;
              items?:
                | T
                | {
                    media?: T;
                    desc?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        projectFeatureGridSection?:
          | T
          | {
              label?: T;
              title?: T;
              subtitle?: T;
              items?:
                | T
                | {
                    iconText?: T;
                    title?: T;
                    desc?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        projectContents?:
          | T
          | {
              name?: T;
              contents?: T;
              id?: T;
              blockName?: T;
            };
        projectTechStackSection?:
          | T
          | {
              label?: T;
              title?: T;
              subtitle?: T;
              items?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              primaryButtonText?: T;
              primaryButtonUrl?: T;
              primaryButtonExternal?: T;
              secondaryButtonText?: T;
              secondaryButtonUrl?: T;
              secondaryButtonExternal?: T;
              id?: T;
              blockName?: T;
            };
        projectCtaSection?:
          | T
          | {
              label?: T;
              title?: T;
              subtitle?: T;
              primaryButtonText?: T;
              primaryButtonUrl?: T;
              primaryButtonExternal?: T;
              secondaryButtonText?: T;
              secondaryButtonUrl?: T;
              secondaryButtonExternal?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project_page_settings".
 */
export interface ProjectPageSetting {
  id: string;
  label?: string | null;
  title?: string | null;
  subtitle?: string | null;
  topPadding?: boolean | null;
  metaTitle?: string | null;
  metaDesc?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_settings".
 */
export interface SiteSetting {
  id: string;
  sitename?: string | null;
  siteDesc?: string | null;
  siteLogoText?: string | null;
  menuItem?:
    | {
        name: string;
        page?: (string | null) | Page;
        id?: string | null;
      }[]
    | null;
  footerText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  showNightModeToggle: boolean;
  showMenuQuickLinksMenu: boolean;
  quickLinks?:
    | {
        name: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project_page_settings_select".
 */
export interface ProjectPageSettingsSelect<T extends boolean = true> {
  label?: T;
  title?: T;
  subtitle?: T;
  topPadding?: T;
  metaTitle?: T;
  metaDesc?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  sitename?: T;
  siteDesc?: T;
  siteLogoText?: T;
  menuItem?:
    | T
    | {
        name?: T;
        page?: T;
        id?: T;
      };
  footerText?: T;
  showNightModeToggle?: T;
  showMenuQuickLinksMenu?: T;
  quickLinks?:
    | T
    | {
        name?: T;
        url?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}