version: '3'

services:
  payload:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
      # - postgres
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-mongodb://mongo/payload}
    restart: unless-stopped

  # Ensure your DATABASE_URL uses 'mongo' as the hostname ie. mongodb://mongo/my-db-name
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

  # Uncomment the following to use postgres
  # postgres:
  #   restart: always
  #   image: postgres:latest
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

volumes:
  data:
  # pgdata:
